// Learned moves — mined from choreographies via dictionary learning + human review.
// Auto-generated by tools/move_mining_pipeline.py — do not edit by hand.

const LEARNED_MOVES = [
  {
    "name": "shuffle",
    "source_song": "Levels by Avicii",
    "source_file": "choreo_3d290c67.json",
    "atom_id": 0,
    "window_sec": 1.0,
    "fps": 15,
    "poses": [
      {
        "t": 0.0,
        "joints": {
          "head": [
            391.7,
            60.6
          ],
          "neck": [
            392.1,
            107.9
          ],
          "leftShoulder": [
            427.2,
            106.4
          ],
          "rightShoulder": [
            357.1,
            109.4
          ],
          "leftElbow": [
            459.1,
            151.8
          ],
          "rightElbow": [
            333.3,
            164.3
          ],
          "leftHand": [
            490.4,
            167.8
          ],
          "rightHand": [
            305.9,
            165.8
          ],
          "hip": [
            393.7,
            222.4
          ],
          "leftKnee": [
            412.5,
            310.5
          ],
          "rightKnee": [
            363.8,
            305.3
          ],
          "leftFoot": [
            422.6,
            418.4
          ],
          "rightFoot": [
            368.0,
            414.8
          ]
        }
      },
      {
        "t": 0.0667,
        "joints": {
          "head": [
            392.4,
            60.6
          ],
          "neck": [
            393.0,
            107.9
          ],
          "leftShoulder": [
            428.0,
            106.4
          ],
          "rightShoulder": [
            357.9,
            109.4
          ],
          "leftElbow": [
            458.8,
            153.8
          ],
          "rightElbow": [
            332.9,
            162.7
          ],
          "leftHand": [
            489.3,
            171.7
          ],
          "rightHand": [
            306.2,
            159.5
          ],
          "hip": [
            395.5,
            222.4
          ],
          "leftKnee": [
            412.8,
            307.7
          ],
          "rightKnee": [
            366.1,
            306.9
          ],
          "leftFoot": [
            425.5,
            416.1
          ],
          "rightFoot": [
            372.7,
            415.8
          ]
        }
      },
      {
        "t": 0.1333,
        "joints": {
          "head": [
            393.1,
            60.6
          ],
          "neck": [
            393.8,
            107.9
          ],
          "leftShoulder": [
            428.8,
            106.4
          ],
          "rightShoulder": [
            358.8,
            109.3
          ],
          "leftElbow": [
            457.7,
            156.0
          ],
          "rightElbow": [
            332.7,
            160.3
          ],
          "leftHand": [
            486.6,
            175.8
          ],
          "rightHand": [
            308.4,
            151.7
          ],
          "hip": [
            397.8,
            222.5
          ],
          "leftKnee": [
            411.8,
            304.6
          ],
          "rightKnee": [
            371.7,
            310.4
          ],
          "leftFoot": [
            425.1,
            413.7
          ],
          "rightFoot": [
            382.9,
            418.4
          ]
        }
      },
      {
        "t": 0.2,
        "joints": {
          "head": [
            393.2,
            60.6
          ],
          "neck": [
            394.0,
            107.7
          ],
          "leftShoulder": [
            428.8,
            106.3
          ],
          "rightShoulder": [
            359.3,
            109.1
          ],
          "leftElbow": [
            455.7,
            157.2
          ],
          "rightElbow": [
            333.1,
            158.2
          ],
          "leftHand": [
            483.4,
            176.6
          ],
          "rightHand": [
            312.8,
            147.3
          ],
          "hip": [
            399.4,
            222.6
          ],
          "leftKnee": [
            408.6,
            303.3
          ],
          "rightKnee": [
            379.8,
            314.9
          ],
          "leftFoot": [
            417.6,
            412.8
          ],
          "rightFoot": [
            396.9,
            421.7
          ]
        }
      },
      {
        "t": 0.2667,
        "joints": {
          "head": [
            392.7,
            60.8
          ],
          "neck": [
            393.6,
            107.7
          ],
          "leftShoulder": [
            428.0,
            106.3
          ],
          "rightShoulder": [
            359.2,
            109.1
          ],
          "leftElbow": [
            453.4,
            157.0
          ],
          "rightElbow": [
            333.5,
            157.2
          ],
          "leftHand": [
            481.2,
            173.3
          ],
          "rightHand": [
            317.2,
            149.0
          ],
          "hip": [
            400.2,
            222.5
          ],
          "leftKnee": [
            405.3,
            303.8
          ],
          "rightKnee": [
            387.3,
            318.4
          ],
          "leftFoot": [
            407.1,
            413.3
          ],
          "rightFoot": [
            408.9,
            423.8
          ]
        }
      },
      {
        "t": 0.3333,
        "joints": {
          "head": [
            392.0,
            61.1
          ],
          "neck": [
            392.9,
            108.0
          ],
          "leftShoulder": [
            427.0,
            106.5
          ],
          "rightShoulder": [
            358.9,
            109.5
          ],
          "leftElbow": [
            452.2,
            156.1
          ],
          "rightElbow": [
            333.3,
            157.7
          ],
          "leftHand": [
            481.5,
            167.0
          ],
          "rightHand": [
            318.5,
            156.8
          ],
          "hip": [
            400.3,
            222.4
          ],
          "leftKnee": [
            404.5,
            305.0
          ],
          "rightKnee": [
            390.6,
            319.0
          ],
          "leftFoot": [
            402.0,
            414.6
          ],
          "rightFoot": [
            413.1,
            423.4
          ]
        }
      },
      {
        "t": 0.4,
        "joints": {
          "head": [
            391.5,
            61.7
          ],
          "neck": [
            392.5,
            109.0
          ],
          "leftShoulder": [
            426.6,
            107.3
          ],
          "rightShoulder": [
            358.5,
            110.6
          ],
          "leftElbow": [
            453.0,
            155.2
          ],
          "rightElbow": [
            332.8,
            159.8
          ],
          "leftHand": [
            483.5,
            158.3
          ],
          "rightHand": [
            316.0,
            168.4
          ],
          "hip": [
            399.9,
            222.5
          ],
          "leftKnee": [
            407.3,
            306.2
          ],
          "rightKnee": [
            388.5,
            316.8
          ],
          "leftFoot": [
            406.8,
            416.1
          ],
          "rightFoot": [
            407.1,
            420.5
          ]
        }
      },
      {
        "t": 0.4667,
        "joints": {
          "head": [
            391.4,
            62.5
          ],
          "neck": [
            392.6,
            110.2
          ],
          "leftShoulder": [
            426.8,
            108.4
          ],
          "rightShoulder": [
            358.4,
            112.0
          ],
          "leftElbow": [
            455.6,
            154.1
          ],
          "rightElbow": [
            332.8,
            163.0
          ],
          "leftHand": [
            484.6,
            147.7
          ],
          "rightHand": [
            312.4,
            179.8
          ],
          "hip": [
            398.9,
            223.1
          ],
          "leftKnee": [
            412.3,
            307.8
          ],
          "rightKnee": [
            383.9,
            313.3
          ],
          "leftFoot": [
            417.5,
            417.4
          ],
          "rightFoot": [
            394.7,
            415.7
          ]
        }
      },
      {
        "t": 0.5333,
        "joints": {
          "head": [
            391.6,
            63.0
          ],
          "neck": [
            392.9,
            110.6
          ],
          "leftShoulder": [
            427.1,
            108.6
          ],
          "rightShoulder": [
            358.7,
            112.6
          ],
          "leftElbow": [
            458.8,
            151.7
          ],
          "rightElbow": [
            334.2,
            165.9
          ],
          "leftHand": [
            482.3,
            135.9
          ],
          "rightHand": [
            311.6,
            188.1
          ],
          "hip": [
            397.6,
            223.6
          ],
          "leftKnee": [
            416.7,
            310.6
          ],
          "rightKnee": [
            381.0,
            310.1
          ],
          "leftFoot": [
            424.8,
            419.1
          ],
          "rightFoot": [
            383.3,
            410.8
          ]
        }
      },
      {
        "t": 0.6,
        "joints": {
          "head": [
            391.6,
            62.7
          ],
          "neck": [
            393.0,
            109.6
          ],
          "leftShoulder": [
            426.7,
            107.6
          ],
          "rightShoulder": [
            359.2,
            111.7
          ],
          "leftElbow": [
            460.6,
            147.9
          ],
          "rightElbow": [
            337.1,
            167.3
          ],
          "leftHand": [
            476.6,
            125.4
          ],
          "rightHand": [
            316.1,
            192.6
          ],
          "hip": [
            395.7,
            223.7
          ],
          "leftKnee": [
            417.6,
            314.3
          ],
          "rightKnee": [
            381.9,
            308.0
          ],
          "leftFoot": [
            421.5,
            421.7
          ],
          "rightFoot": [
            379.6,
            408.4
          ]
        }
      },
      {
        "t": 0.6667,
        "joints": {
          "head": [
            391.3,
            61.9
          ],
          "neck": [
            392.6,
            107.8
          ],
          "leftShoulder": [
            425.5,
            105.9
          ],
          "rightShoulder": [
            359.6,
            109.7
          ],
          "leftElbow": [
            460.4,
            143.7
          ],
          "rightElbow": [
            341.0,
            167.2
          ],
          "leftHand": [
            470.2,
            119.3
          ],
          "rightHand": [
            324.3,
            193.7
          ],
          "hip": [
            393.4,
            223.2
          ],
          "leftKnee": [
            413.4,
            317.7
          ],
          "rightKnee": [
            385.9,
            306.6
          ],
          "leftFoot": [
            408.3,
            424.7
          ],
          "rightFoot": [
            385.2,
            409.1
          ]
        }
      },
      {
        "t": 0.7333,
        "joints": {
          "head": [
            390.9,
            61.2
          ],
          "neck": [
            391.8,
            106.3
          ],
          "leftShoulder": [
            424.1,
            104.6
          ],
          "rightShoulder": [
            359.6,
            108.0
          ],
          "leftElbow": [
            458.6,
            140.9
          ],
          "rightElbow": [
            344.1,
            166.5
          ],
          "leftHand": [
            467.0,
            120.2
          ],
          "rightHand": [
            331.3,
            192.4
          ],
          "hip": [
            391.5,
            222.6
          ],
          "leftKnee": [
            406.3,
            319.7
          ],
          "rightKnee": [
            389.3,
            305.1
          ],
          "leftFoot": [
            393.1,
            426.7
          ],
          "rightFoot": [
            395.5,
            411.0
          ]
        }
      },
      {
        "t": 0.8,
        "joints": {
          "head": [
            390.1,
            60.8
          ],
          "neck": [
            390.9,
            105.7
          ],
          "leftShoulder": [
            423.0,
            104.1
          ],
          "rightShoulder": [
            358.8,
            107.3
          ],
          "leftElbow": [
            456.6,
            140.9
          ],
          "rightElbow": [
            344.8,
            166.4
          ],
          "leftHand": [
            469.1,
            128.4
          ],
          "rightHand": [
            332.2,
            190.0
          ],
          "hip": [
            390.4,
            222.3
          ],
          "leftKnee": [
            400.5,
            320.1
          ],
          "rightKnee": [
            388.6,
            303.4
          ],
          "leftFoot": [
            384.4,
            426.9
          ],
          "rightFoot": [
            402.4,
            411.9
          ]
        }
      },
      {
        "t": 0.8667,
        "joints": {
          "head": [
            388.9,
            60.7
          ],
          "neck": [
            389.8,
            106.1
          ],
          "leftShoulder": [
            422.5,
            104.4
          ],
          "rightShoulder": [
            357.2,
            107.7
          ],
          "leftElbow": [
            455.3,
            143.0
          ],
          "rightElbow": [
            343.1,
            167.4
          ],
          "leftHand": [
            474.7,
            140.3
          ],
          "rightHand": [
            327.0,
            187.4
          ],
          "hip": [
            389.8,
            222.5
          ],
          "leftKnee": [
            398.0,
            319.5
          ],
          "rightKnee": [
            383.6,
            301.9
          ],
          "leftFoot": [
            384.1,
            426.4
          ],
          "rightFoot": [
            402.2,
            412.1
          ]
        }
      },
      {
        "t": 0.9333,
        "joints": {
          "head": [
            387.9,
            60.7
          ],
          "neck": [
            389.1,
            106.5
          ],
          "leftShoulder": [
            422.4,
            104.8
          ],
          "rightShoulder": [
            355.8,
            108.2
          ],
          "leftElbow": [
            454.7,
            145.1
          ],
          "rightElbow": [
            341.1,
            168.5
          ],
          "leftHand": [
            479.4,
            149.1
          ],
          "rightHand": [
            321.6,
            185.6
          ],
          "hip": [
            389.6,
            222.9
          ],
          "leftKnee": [
            397.9,
            318.9
          ],
          "rightKnee": [
            378.6,
            301.1
          ],
          "leftFoot": [
            386.8,
            426.0
          ],
          "rightFoot": [
            398.8,
            412.1
          ]
        }
      }
    ],
    "energy": "high",
    "durationBeats": 4,
    "type": "full-body",
    "keyframes": [
      {
        "time": 0.0,
        "pose": {
          "head": {
            "x": -8.3,
            "y": -59.4
          },
          "neck": {
            "x": -7.9,
            "y": -47.1
          },
          "leftShoulder": {
            "x": 67.2,
            "y": -58.6
          },
          "rightShoulder": {
            "x": -82.9,
            "y": -55.6
          },
          "leftElbow": {
            "x": 129.1,
            "y": -68.2
          },
          "rightElbow": {
            "x": -136.7,
            "y": -55.7
          },
          "leftHand": {
            "x": 180.4,
            "y": -102.2
          },
          "rightHand": {
            "x": -184.1,
            "y": -104.2
          },
          "hip": {
            "x": -6.3,
            "y": -57.6
          },
          "leftKnee": {
            "x": 37.5,
            "y": -49.5
          },
          "rightKnee": {
            "x": -61.2,
            "y": -54.7
          },
          "leftFoot": {
            "x": 57.6,
            "y": -21.6
          },
          "rightFoot": {
            "x": -67.0,
            "y": -25.2
          }
        }
      },
      {
        "time": 0.25,
        "pose": {
          "head": {
            "x": -6.8,
            "y": -59.4
          },
          "neck": {
            "x": -6.0,
            "y": -47.3
          },
          "leftShoulder": {
            "x": 68.8,
            "y": -58.7
          },
          "rightShoulder": {
            "x": -80.7,
            "y": -55.9
          },
          "leftElbow": {
            "x": 125.7,
            "y": -62.8
          },
          "rightElbow": {
            "x": -136.9,
            "y": -61.8
          },
          "leftHand": {
            "x": 173.4,
            "y": -93.4
          },
          "rightHand": {
            "x": -177.2,
            "y": -122.7
          },
          "hip": {
            "x": -0.6,
            "y": -57.4
          },
          "leftKnee": {
            "x": 33.6,
            "y": -56.7
          },
          "rightKnee": {
            "x": -45.2,
            "y": -45.1
          },
          "leftFoot": {
            "x": 52.6,
            "y": -27.2
          },
          "rightFoot": {
            "x": -38.1,
            "y": -18.3
          }
        }
      },
      {
        "time": 0.5,
        "pose": {
          "head": {
            "x": -8.6,
            "y": -57.5
          },
          "neck": {
            "x": -7.4,
            "y": -44.8
          },
          "leftShoulder": {
            "x": 66.8,
            "y": -56.6
          },
          "rightShoulder": {
            "x": -81.6,
            "y": -53.0
          },
          "leftElbow": {
            "x": 125.6,
            "y": -65.9
          },
          "rightElbow": {
            "x": -137.2,
            "y": -57.0
          },
          "leftHand": {
            "x": 174.6,
            "y": -122.3
          },
          "rightHand": {
            "x": -177.6,
            "y": -90.2
          },
          "hip": {
            "x": -1.1,
            "y": -56.9
          },
          "leftKnee": {
            "x": 37.3,
            "y": -52.2
          },
          "rightKnee": {
            "x": -41.1,
            "y": -46.7
          },
          "leftFoot": {
            "x": 52.5,
            "y": -22.6
          },
          "rightFoot": {
            "x": -40.3,
            "y": -24.3
          }
        }
      },
      {
        "time": 0.75,
        "pose": {
          "head": {
            "x": -9.1,
            "y": -58.8
          },
          "neck": {
            "x": -8.2,
            "y": -48.7
          },
          "leftShoulder": {
            "x": 64.1,
            "y": -60.4
          },
          "rightShoulder": {
            "x": -80.4,
            "y": -57.0
          },
          "leftElbow": {
            "x": 128.6,
            "y": -79.1
          },
          "rightElbow": {
            "x": -125.9,
            "y": -53.5
          },
          "leftHand": {
            "x": 157.0,
            "y": -149.8
          },
          "rightHand": {
            "x": -158.7,
            "y": -77.6
          },
          "hip": {
            "x": -8.5,
            "y": -57.4
          },
          "leftKnee": {
            "x": 31.3,
            "y": -40.3
          },
          "rightKnee": {
            "x": -35.7,
            "y": -54.9
          },
          "leftFoot": {
            "x": 28.1,
            "y": -13.3
          },
          "rightFoot": {
            "x": -39.5,
            "y": -29.0
          }
        }
      },
      {
        "time": 1.0,
        "pose": {}
      }
    ],
    "source": "learned"
  },
  {
    "name": "wiggle",
    "source_song": "Macarena by Los del Rio",
    "source_file": "choreo_1c8fc6ab.json",
    "atom_id": 7,
    "window_sec": 1.0,
    "fps": 15,
    "poses": [
      {
        "t": 0.0,
        "joints": {
          "head": [
            398.3,
            60.0
          ],
          "neck": [
            397.8,
            109.4
          ],
          "leftShoulder": [
            431.8,
            108.9
          ],
          "rightShoulder": [
            363.8,
            109.9
          ],
          "leftElbow": [
            443.3,
            160.8
          ],
          "rightElbow": [
            357.7,
            155.7
          ],
          "leftHand": [
            444.3,
            166.2
          ],
          "rightHand": [
            363.8,
            156.3
          ],
          "hip": [
            405.6,
            228.4
          ],
          "leftKnee": [
            446.7,
            340.1
          ],
          "rightKnee": [
            361.8,
            341.0
          ],
          "leftFoot": [
            456.9,
            438.0
          ],
          "rightFoot": [
            345.6,
            438.2
          ]
        }
      },
      {
        "t": 0.0667,
        "joints": {
          "head": [
            397.8,
            60.0
          ],
          "neck": [
            397.1,
            109.5
          ],
          "leftShoulder": [
            431.1,
            109.2
          ],
          "rightShoulder": [
            363.2,
            109.9
          ],
          "leftElbow": [
            443.2,
            160.6
          ],
          "rightElbow": [
            356.9,
            155.7
          ],
          "leftHand": [
            444.3,
            165.0
          ],
          "rightHand": [
            362.3,
            157.7
          ],
          "hip": [
            403.9,
            228.4
          ],
          "leftKnee": [
            446.1,
            340.1
          ],
          "rightKnee": [
            361.2,
            341.3
          ],
          "leftFoot": [
            456.7,
            438.0
          ],
          "rightFoot": [
            345.2,
            438.5
          ]
        }
      },
      {
        "t": 0.1333,
        "joints": {
          "head": [
            396.8,
            60.0
          ],
          "neck": [
            396.3,
            109.7
          ],
          "leftShoulder": [
            430.1,
            109.4
          ],
          "rightShoulder": [
            362.4,
            109.9
          ],
          "leftElbow": [
            443.0,
            160.4
          ],
          "rightElbow": [
            355.8,
            156.1
          ],
          "leftHand": [
            443.9,
            163.4
          ],
          "rightHand": [
            360.1,
            159.5
          ],
          "hip": [
            401.3,
            228.5
          ],
          "leftKnee": [
            445.2,
            340.0
          ],
          "rightKnee": [
            360.1,
            341.5
          ],
          "leftFoot": [
            456.0,
            438.0
          ],
          "rightFoot": [
            344.7,
            438.7
          ]
        }
      },
      {
        "t": 0.2,
        "joints": {
          "head": [
            395.9,
            60.0
          ],
          "neck": [
            395.8,
            109.7
          ],
          "leftShoulder": [
            429.5,
            109.5
          ],
          "rightShoulder": [
            362.1,
            110.0
          ],
          "leftElbow": [
            442.9,
            160.0
          ],
          "rightElbow": [
            355.1,
            157.1
          ],
          "leftHand": [
            443.4,
            161.8
          ],
          "rightHand": [
            358.2,
            160.5
          ],
          "hip": [
            398.7,
            228.7
          ],
          "leftKnee": [
            444.4,
            339.7
          ],
          "rightKnee": [
            358.7,
            341.3
          ],
          "leftFoot": [
            455.3,
            438.0
          ],
          "rightFoot": [
            344.5,
            438.7
          ]
        }
      },
      {
        "t": 0.2667,
        "joints": {
          "head": [
            395.5,
            60.0
          ],
          "neck": [
            396.1,
            109.6
          ],
          "leftShoulder": [
            429.8,
            109.0
          ],
          "rightShoulder": [
            362.5,
            110.2
          ],
          "leftElbow": [
            442.9,
            159.4
          ],
          "rightElbow": [
            354.9,
            158.1
          ],
          "leftHand": [
            443.1,
            160.5
          ],
          "rightHand": [
            356.9,
            160.4
          ],
          "hip": [
            396.9,
            228.7
          ],
          "leftKnee": [
            443.9,
            339.6
          ],
          "rightKnee": [
            357.3,
            340.5
          ],
          "leftFoot": [
            455.0,
            437.9
          ],
          "rightFoot": [
            344.7,
            438.5
          ]
        }
      },
      {
        "t": 0.3333,
        "joints": {
          "head": [
            395.5,
            60.1
          ],
          "neck": [
            397.1,
            109.4
          ],
          "leftShoulder": [
            430.8,
            108.3
          ],
          "rightShoulder": [
            363.4,
            110.5
          ],
          "leftElbow": [
            443.1,
            158.5
          ],
          "rightElbow": [
            354.8,
            158.5
          ],
          "leftHand": [
            443.4,
            159.8
          ],
          "rightHand": [
            356.2,
            159.5
          ],
          "hip": [
            396.2,
            228.6
          ],
          "leftKnee": [
            443.5,
            339.8
          ],
          "rightKnee": [
            356.3,
            339.6
          ],
          "leftFoot": [
            455.4,
            437.8
          ],
          "rightFoot": [
            345.4,
            438.0
          ]
        }
      },
      {
        "t": 0.4,
        "joints": {
          "head": [
            395.6,
            60.4
          ],
          "neck": [
            398.2,
            109.4
          ],
          "leftShoulder": [
            431.8,
            107.7
          ],
          "rightShoulder": [
            364.5,
            111.1
          ],
          "leftElbow": [
            443.3,
            157.6
          ],
          "rightElbow": [
            354.6,
            158.5
          ],
          "leftHand": [
            444.2,
            160.5
          ],
          "rightHand": [
            355.4,
            158.3
          ],
          "hip": [
            396.1,
            228.6
          ],
          "leftKnee": [
            442.6,
            340.3
          ],
          "rightKnee": [
            355.5,
            338.7
          ],
          "leftFoot": [
            456.1,
            437.9
          ],
          "rightFoot": [
            346.2,
            437.6
          ]
        }
      },
      {
        "t": 0.4667,
        "joints": {
          "head": [
            395.7,
            60.9
          ],
          "neck": [
            399.2,
            109.7
          ],
          "leftShoulder": [
            432.7,
            107.4
          ],
          "rightShoulder": [
            365.7,
            111.9
          ],
          "leftElbow": [
            443.7,
            157.3
          ],
          "rightElbow": [
            354.0,
            158.4
          ],
          "leftHand": [
            444.9,
            163.0
          ],
          "rightHand": [
            354.2,
            157.0
          ],
          "hip": [
            396.7,
            228.8
          ],
          "leftKnee": [
            441.5,
            340.9
          ],
          "rightKnee": [
            355.0,
            338.1
          ],
          "leftFoot": [
            457.0,
            438.0
          ],
          "rightFoot": [
            347.1,
            437.4
          ]
        }
      },
      {
        "t": 0.5333,
        "joints": {
          "head": [
            396.1,
            61.5
          ],
          "neck": [
            400.4,
            110.1
          ],
          "leftShoulder": [
            433.8,
            107.4
          ],
          "rightShoulder": [
            367.0,
            112.8
          ],
          "leftElbow": [
            444.5,
            157.7
          ],
          "rightElbow": [
            353.6,
            158.4
          ],
          "leftHand": [
            445.1,
            167.1
          ],
          "rightHand": [
            352.9,
            155.5
          ],
          "hip": [
            397.9,
            229.1
          ],
          "leftKnee": [
            440.5,
            341.5
          ],
          "rightKnee": [
            355.1,
            337.8
          ],
          "leftFoot": [
            458.2,
            438.1
          ],
          "rightFoot": [
            348.3,
            437.6
          ]
        }
      },
      {
        "t": 0.6,
        "joints": {
          "head": [
            396.9,
            61.9
          ],
          "neck": [
            401.9,
            110.4
          ],
          "leftShoulder": [
            435.3,
            107.4
          ],
          "rightShoulder": [
            368.6,
            113.4
          ],
          "leftElbow": [
            445.5,
            158.2
          ],
          "rightElbow": [
            353.8,
            158.2
          ],
          "leftHand": [
            444.6,
            171.4
          ],
          "rightHand": [
            351.9,
            153.3
          ],
          "hip": [
            399.8,
            229.3
          ],
          "leftKnee": [
            440.2,
            342.0
          ],
          "rightKnee": [
            355.8,
            337.8
          ],
          "leftFoot": [
            459.5,
            438.1
          ],
          "rightFoot": [
            349.8,
            438.0
          ]
        }
      },
      {
        "t": 0.6667,
        "joints": {
          "head": [
            398.0,
            62.2
          ],
          "neck": [
            403.6,
            110.5
          ],
          "leftShoulder": [
            436.8,
            107.4
          ],
          "rightShoulder": [
            370.4,
            113.7
          ],
          "leftElbow": [
            446.3,
            158.5
          ],
          "rightElbow": [
            354.8,
            157.4
          ],
          "leftHand": [
            443.5,
            174.8
          ],
          "rightHand": [
            351.4,
            150.0
          ],
          "hip": [
            402.0,
            229.5
          ],
          "leftKnee": [
            440.7,
            342.2
          ],
          "rightKnee": [
            356.9,
            337.8
          ],
          "leftFoot": [
            460.4,
            437.9
          ],
          "rightFoot": [
            351.3,
            438.3
          ]
        }
      },
      {
        "t": 0.7333,
        "joints": {
          "head": [
            399.1,
            62.3
          ],
          "neck": [
            404.9,
            110.4
          ],
          "leftShoulder": [
            437.8,
            107.2
          ],
          "rightShoulder": [
            371.9,
            113.6
          ],
          "leftElbow": [
            446.7,
            158.6
          ],
          "rightElbow": [
            356.2,
            156.1
          ],
          "leftHand": [
            442.1,
            176.8
          ],
          "rightHand": [
            351.5,
            146.2
          ],
          "hip": [
            404.2,
            229.5
          ],
          "leftKnee": [
            441.6,
            342.3
          ],
          "rightKnee": [
            357.8,
            337.9
          ],
          "leftFoot": [
            460.2,
            437.6
          ],
          "rightFoot": [
            352.4,
            438.4
          ]
        }
      },
      {
        "t": 0.8,
        "joints": {
          "head": [
            399.9,
            62.3
          ],
          "neck": [
            405.6,
            110.3
          ],
          "leftShoulder": [
            438.3,
            107.2
          ],
          "rightShoulder": [
            372.9,
            113.4
          ],
          "leftElbow": [
            446.9,
            158.6
          ],
          "rightElbow": [
            357.8,
            154.4
          ],
          "leftHand": [
            440.9,
            177.4
          ],
          "rightHand": [
            352.2,
            142.9
          ],
          "hip": [
            406.2,
            229.7
          ],
          "leftKnee": [
            442.3,
            342.1
          ],
          "rightKnee": [
            358.5,
            337.8
          ],
          "leftFoot": [
            458.8,
            437.4
          ],
          "rightFoot": [
            352.8,
            438.2
          ]
        }
      },
      {
        "t": 0.8667,
        "joints": {
          "head": [
            400.2,
            62.3
          ],
          "neck": [
            405.8,
            110.2
          ],
          "leftShoulder": [
            438.3,
            107.2
          ],
          "rightShoulder": [
            373.2,
            113.2
          ],
          "leftElbow": [
            446.9,
            158.6
          ],
          "rightElbow": [
            359.2,
            153.1
          ],
          "leftHand": [
            440.0,
            177.2
          ],
          "rightHand": [
            353.3,
            140.8
          ],
          "hip": [
            407.7,
            229.7
          ],
          "leftKnee": [
            442.6,
            341.8
          ],
          "rightKnee": [
            359.0,
            337.6
          ],
          "leftFoot": [
            457.0,
            437.2
          ],
          "rightFoot": [
            352.7,
            437.7
          ]
        }
      },
      {
        "t": 0.9333,
        "joints": {
          "head": [
            400.3,
            62.3
          ],
          "neck": [
            405.7,
            110.1
          ],
          "leftShoulder": [
            438.2,
            107.2
          ],
          "rightShoulder": [
            373.2,
            113.0
          ],
          "leftElbow": [
            446.9,
            158.6
          ],
          "rightElbow": [
            360.0,
            152.5
          ],
          "leftHand": [
            439.6,
            176.9
          ],
          "rightHand": [
            354.1,
            140.0
          ],
          "hip": [
            408.4,
            229.8
          ],
          "leftKnee": [
            442.7,
            341.6
          ],
          "rightKnee": [
            359.2,
            337.3
          ],
          "leftFoot": [
            455.8,
            437.1
          ],
          "rightFoot": [
            352.6,
            437.4
          ]
        }
      }
    ],
    "energy": "mid",
    "durationBeats": 4,
    "type": "full-body",
    "keyframes": [
      {
        "time": 0.0,
        "pose": {
          "head": {
            "x": -1.7,
            "y": -60.0
          },
          "neck": {
            "x": -2.2,
            "y": -45.6
          },
          "leftShoulder": {
            "x": 71.8,
            "y": -56.1
          },
          "rightShoulder": {
            "x": -76.2,
            "y": -55.1
          },
          "leftElbow": {
            "x": 113.3,
            "y": -59.2
          },
          "rightElbow": {
            "x": -112.3,
            "y": -64.3
          },
          "leftHand": {
            "x": 134.3,
            "y": -103.8
          },
          "rightHand": {
            "x": -126.2,
            "y": -113.7
          },
          "hip": {
            "x": 5.6,
            "y": -51.6
          },
          "leftKnee": {
            "x": 71.7,
            "y": -19.9
          },
          "rightKnee": {
            "x": -63.2,
            "y": -19.0
          },
          "leftFoot": {
            "x": 91.9,
            "y": -2.0
          },
          "rightFoot": {
            "x": -89.4,
            "y": -1.8
          }
        }
      },
      {
        "time": 0.25,
        "pose": {
          "head": {
            "x": -4.1,
            "y": -60.0
          },
          "neck": {
            "x": -4.2,
            "y": -45.3
          },
          "leftShoulder": {
            "x": 69.5,
            "y": -55.5
          },
          "rightShoulder": {
            "x": -77.9,
            "y": -55.0
          },
          "leftElbow": {
            "x": 112.9,
            "y": -60.0
          },
          "rightElbow": {
            "x": -114.9,
            "y": -62.9
          },
          "leftHand": {
            "x": 133.4,
            "y": -108.2
          },
          "rightHand": {
            "x": -131.8,
            "y": -109.5
          },
          "hip": {
            "x": -1.3,
            "y": -51.3
          },
          "leftKnee": {
            "x": 69.4,
            "y": -20.3
          },
          "rightKnee": {
            "x": -66.3,
            "y": -18.7
          },
          "leftFoot": {
            "x": 90.3,
            "y": -2.0
          },
          "rightFoot": {
            "x": -90.5,
            "y": -1.3
          }
        }
      },
      {
        "time": 0.5,
        "pose": {
          "head": {
            "x": -4.3,
            "y": -59.1
          },
          "neck": {
            "x": -0.8,
            "y": -45.3
          },
          "leftShoulder": {
            "x": 72.7,
            "y": -57.6
          },
          "rightShoulder": {
            "x": -74.3,
            "y": -53.1
          },
          "leftElbow": {
            "x": 113.7,
            "y": -62.7
          },
          "rightElbow": {
            "x": -116.0,
            "y": -61.6
          },
          "leftHand": {
            "x": 134.9,
            "y": -107.0
          },
          "rightHand": {
            "x": -135.8,
            "y": -113.0
          },
          "hip": {
            "x": -3.3,
            "y": -51.2
          },
          "leftKnee": {
            "x": 66.5,
            "y": -19.1
          },
          "rightKnee": {
            "x": -70.0,
            "y": -21.9
          },
          "leftFoot": {
            "x": 92.0,
            "y": -2.0
          },
          "rightFoot": {
            "x": -87.9,
            "y": -2.6
          }
        }
      },
      {
        "time": 0.75,
        "pose": {
          "head": {
            "x": -0.9,
            "y": -57.7
          },
          "neck": {
            "x": 4.9,
            "y": -44.6
          },
          "leftShoulder": {
            "x": 77.8,
            "y": -57.8
          },
          "rightShoulder": {
            "x": -68.1,
            "y": -51.4
          },
          "leftElbow": {
            "x": 116.7,
            "y": -61.4
          },
          "rightElbow": {
            "x": -113.8,
            "y": -63.9
          },
          "leftHand": {
            "x": 132.1,
            "y": -93.2
          },
          "rightHand": {
            "x": -138.5,
            "y": -123.8
          },
          "hip": {
            "x": 4.2,
            "y": -50.5
          },
          "leftKnee": {
            "x": 66.6,
            "y": -17.7
          },
          "rightKnee": {
            "x": -67.2,
            "y": -22.1
          },
          "leftFoot": {
            "x": 95.2,
            "y": -2.4
          },
          "rightFoot": {
            "x": -82.6,
            "y": -1.6
          }
        }
      },
      {
        "time": 1.0,
        "pose": {}
      }
    ],
    "source": "learned"
  }
];
